version: 1.0.{build}
image: Visual Studio 2017
before_build:
- nuget restore OniBot.sln
build:
  project: OniBot.sln
  verbosity: minimal
notifications:
- provider: Webhook
  url: https://discordapp.com/api/webhooks/289629464235737089/W2YIcUm6hdKgGNRnHCMOpctdG5WQAuq9k-pLysF6Bcv151ZGs4CkZVwu0qdVIJNivDnJ
  method: POST
  body: >-
    {
    "content": "Build **{{status}}**: {{projectName}} {{buildVersion}}",
    "username": "AppVeyor",
    "avatar_url": "https://pbs.twimg.com/profile_images/2269442372/5s66pnbt5v8tw6most5e.png",
    "tts": false
    }
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
