version: 1.0.{build}
image: Visual Studio 2017

install:
- ps: choco install docker-compose
- cmd: docker version

before_build:
- nuget restore OniBot.sln

build:
  project: OniBot.sln
  verbosity: minimal

platform: Any CPU
configuration: Release

test: off  

artifacts:  
- path: OniBot\bin\$(configuration)\netcoreapp1.1
  name: Release

deploy:
- provider: GitHub
  auth_token:
    secure: LpWUNFuHR3+5I1gSO10HZta7xDC3oY/WKzSTSFdc8y3axHbmy2Q92EWCssT7tgd/

environment:
  DOCKER_USER:
    secure: ry9x9cQ9gzMNaPOd45RSHQ==
  DOCKER_PASS:
    secure: AXXeju7g+0ZE1ZMW2TKcXfW6+CMT70ZDh5iWYE5Bg80=

deploy_script:
 - ps: .\deploy.ps1
