version: 1.0.{build}
image: Visual Studio 2017

install:
- ps: (New-Object Net.WebClient).DownloadFile('https://github.com/docker/compose/releases/download/1.11.2/docker-compose-Windows-x86_64.exe', "C:\Program Files\docker\docker-compose.exe")
- cmd: docker version

before_build:
- nuget restore OniBot.sln

build:
  project: OniBot.sln
  verbosity: minimal

platform: Any CPU
configuration: Release

test: off  

artifacts:  
- path: OniBot\bin\$(configuration)\netcoreapp1.1
  name: Release

deploy:
- provider: GitHub
  auth_token:
    secure: LpWUNFuHR3+5I1gSO10HZta7xDC3oY/WKzSTSFdc8y3axHbmy2Q92EWCssT7tgd/

environment:
  DOCKER_USER:
    secure: ry9x9cQ9gzMNaPOd45RSHQ==
  DOCKER_PASS:
    secure: AXXeju7g+0ZE1ZMW2TKcXfW6+CMT70ZDh5iWYE5Bg80=

deploy_script:
 - ps: .\deploy.ps1

notifications:
- provider: Webhook
  url: 
    secure:fELG/oUdNsV+J65yan2ZYCLGHnWdx2x5KzKIwtdLaEwsJ2d5D579NqW12ro/wMT8tGEDOvNaiy9OtSPwPIzzA81YLLD5tFgg3dwapDBdndRAYGkrSnRDht5wwiMqJ03qlIjeB2S3LM3jA8HjjRdooEc3tmnkKdC7SWXwrbE758Y=
  method: POST
  body: >-
    {
        "content": "Build **{{status}}**: {{projectName}} {{buildVersion}}\n{{commitMessage}}\n{{commitId}}",
        "username": "AppVeyor",
        "avatar_url": "https://pbs.twimg.com/profile_images/2269442372/5s66pnbt5v8tw6most5e.png",
        "tts": false
    }
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true