version: '2.1'

services:
  onibot:
    build:
      args:
        source: ${DOCKER_BUILD_SOURCE}
    volumes:
      - c:/users/ccurw/clrdbg:c:/clrdbg:ro
    labels:
      - "com.microsoft.visualstudio.targetoperatingsystem=windows"
networks:
  default:
    external:
      name: nat