version: '2.1'

services:
  onibot:
    image: onibot:dev
    build:
      args:
        source: ${DOCKER_BUILD_SOURCE}
    volumes:
      - ./OniBot:c:/app
      - ~/clrdbg:/clrdbg:ro
    entrypoint: tail -f /dev/null
    labels:
      - "com.microsoft.visualstudio.targetoperatingsystem=windows"
networks:
  default:
    external:
      name: nat