version: 2
jobs:
  build:
    docker:
      - image: alpine:latest
    steps:
      - checkout
      - setup_remote_docker:
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.09.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker build -t cisien/onibot:$CIRCLE_BRANCH . -f OniBot/Dockerfile
            docker push cisien/onibot:$CIRCLE_BRANCH
